config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :posts do
    resources :comments
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "https://c2.staticflickr.com/6/5049/5236758661_9501985314_b.jpg"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTpeo_EKa2Sd9ZstbR-dKsqgLoijbeYlCMFVikOwdehcz2HV8MTDTyh1Ag"
         validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :image, :performer])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar)}
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.where(post_id: params[:post_id])
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params) # here we use our comment_params method
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@comment.post_id)
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])

  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(comment_params) #here we use our comment_params method
      redirect_to post_path(params[:post_id])
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @category  = Category.all
  end

  def create
    @post = Post.new(post_params) # here we use our post_params method
    @post.user = current_user

    if @post.save
      redirect_to :posts
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @category  = Category.all
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params) #here we use our post_params method
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:headline, :occured, :content, :performer_website, :performer_info, :user_id, :image, :category_id)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      if user_signed_in?
      redirect_to posts_path
      end
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<h1>Edit this comment!</h1>

  <%= form_for [@post, @comment] do |f| %>

      <div>
          <%= f.label :content %>
          <%= f.text_area :content, size: "40x5" %>
      </div>
      <br>

      <%= f.submit "Submit these changes!" %>

  <% end %>

<%= link_to "Back to the list!", post_path %>

app/views/comments/index.html.erb
<h1>Today's Comments</h1>

<ul>
    <% @comments.each do |comment| %>
        <li>
            <strong> <%= comment.content %> </strong> - made by <%=comment.user_id %>
	     <%= link_to "Back to post", post_path(comment) %>  |  <%= link_to "Back to all posts!", posts_path %>
        </li>
    <% end %>
</ul>

app/views/comments/new.html.erb
<div class="container">
    <h1 class="specialCh">Add a new comment</h1>

  <%= form_for [@post, @comment], html: {class: 'form-horizontal'} do |f| %>

      <div class="form-group">
          <%= f.label :content, class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_area :content, size: "40x2", class: "form-control" %>
          </div>
      </div>
      <br>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit "Submit", class: "btn btn-primary form-control" %>
        </div>
      </div>

      <% end %>

      <div style="padding-left: 17%;">

          <%= link_to "Back to the list!", posts_path %>
      </div>

</div>

app/views/comments/show.html.erb
<h1> <%= @comment.content %> </h1>

<p> <%= @comment.content %> <br><br>
  posted by <%=link_to @comment.user.username %>  <br>
  in response to <%=link_to @comment.post_id %> </p>


<%= link_to "Edit”, edit_post_comment_path(@comment) %>

<%= link_to "Back to the list!", post_comments_path %>  <%= link_to "Delete", post_comment_path, method: :delete, data: { confirm: "Are you sure you want to delete this?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buskr</title>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Buskr", root_path, class: "navbar-brand specialCh" %>
        <!-- <a class="navbar-brand" href="/posts">Perfinder</a> -->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="navbar-text navbar-right">

          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>



          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>

        </ul>


      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="container">
    <h1 class="specialCh">Edit this post!</h1>

    <%= form_for @post, html: {class: 'form-horizontal'} do |f| %>

        <div class="form-group">
            <%= f.label :headline, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :headline, class: "form-control" %>
            </div>

        </div>

        <div class="form-group">
            <%= f.label :content, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_area :content, size: "30x1", class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :occured, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :occured, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :performer_website, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :performer_website, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :performer_info, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :performer_info, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :category_id, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.collection_select(:category_id, @category, :id, :name, class: "form-control") %>
            </div>
        </div>

        <!-- <div class="form-group">
            <%= f.label :image, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :image, class: "form-control" %>
            </div>
        </div> -->

        <div class="form-group">
            <%= f.label :picture, class: 'col-sm-2 control-label'  %>
            <div class="col-sm-6">
                <%= f.file_field :picture %>
            </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "Submit these changes", class: "btn btn-primary form-control" %>
          </div>
        </div>

    <% end %>

    <div style="padding-left: 17%;">

        <%= link_to "Back to the list!", posts_path %>
    </div>


</div>

app/views/posts/index.html.erb
<div class="container">
    <h1 class="specialCh">Posts</h1>

    <div>
      <% if current_user %>
         Write a <%= link_to "New Post", new_post_path(@post) %>
      <% elsif %>
         Write a <%= link_to "New Post", new_user_session_path  %>
      <% end %>
    </div>
    <br>

    <ul>
        <% @posts.each do |post| %>
        <div class="panel panel-primary" role="post">
            <div class="panel-heading"><strong class="specialCh"><h4> <%= post.headline %> </h4></strong></div>
                 <div class="panel-body"><%= post.content %> <br>
                <% if post.user %>
                  by <strong> <%= post.user.username %> </strong>
                <% end %>
    	     <%= link_to "View", post_path(post) %>  |

           <% if current_user %>
              <%= link_to "Comment", new_post_comment_path(post) %>
           <% elsif %>
              <%= link_to "Comment", new_user_session_path  %>
           <% end %>

           <!-- <div class="media-left">
             <a href="#">
               <img class="media-object" src="@post.picture.url" alt="...">
             </a>
           </div> -->

         </div>
        </div>
        <% end %>
    </ul>
</div>

app/views/posts/new.html.erb
<div class="container">
    <h1 class="specialCh">Add a new post!</h1>

    <%= form_for @post, html: {class: 'form-horizontal'} do |f| %>

        <div class="form-group">
            <%= f.label :headline, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :headline, class: "form-control" %>
            </div>

        </div>

        <div class="form-group">
            <%= f.label :content, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_area :content, size: "30x1", class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :occured, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :occured, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :performer_website, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :performer_website, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :performer_info, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :performer_info, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :category_id, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.collection_select(:category_id, @category, :id, :name, class: "form-control") %>
            </div>
        </div>

        <!-- <div class="form-group">
            <%= f.label :image, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :image, class: "form-control" %>
            </div>
        </div> -->

        <div class="form-group">
            <%= f.label :avatar, class: 'col-sm-2 control-label'  %>
            <div class="col-sm-6">
                <%= f.file_field :avatar %>
            </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "Submit", class: "btn btn-primary form-control" %>
          </div>
        </div>

    <% end %>

    <div style="padding-left: 17%;">

        <%= link_to "Back to the list!", posts_path %>
    </div>


</div>

app/views/posts/show.html.erb
<div class="container">
    <h1 class="specialCh"> <%= @post.headline %> </h1>


    <% if current_user %>

    <% if @post.user_id == current_user.id %>
    <%= link_to "Edit", edit_post_path(@post) %> | <%= link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure you want to delete this?"} %>
    <% end %>

    <% end %>

    <br>
    <!-- &nbsp; <%= link_to "Edit", edit_post_path(@post) %> -->


  <div class="alert alert-info" role="alert">
    <div class="round-image-100 navbar-text navbar-right"><%= image_tag(@post.picture(:medium)) %></div>
    <p> <%= @post.content %> <br><br>
    When I saw them: <%= @post.occured %> <br><br>
    Performer Website: <%= @post.performer_website %> <br><br>
    Performer Info: <%= @post.performer_info %>

    <br><br><br><br>

    <p><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>      <strong>Comments for this post:</strong></p>

    <% @post.comments.each do |comment| %>

      *<%=  comment.content %>* by <em> <%= comment.user.username %> </em><br>

    <% if current_user %>

      <% if comment.user_id == current_user.id %>
      <%= link_to "Edit", edit_post_comment_path(@post, comment) %> | <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this?"} %> <br>
      <% end %>
    <% end %>

    <% end %>
    <br><br>

    <% if current_user %>
       leave a <%= link_to "Comment", new_post_comment_path(@post) %>
    <% elsif %>
       leave a <%= link_to "Comment", new_user_session_path  %>
    <% end %>

    </p>
  </div>

    <div>
      <%= link_to "Back to posts!", posts_path %>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="specialCh">Buskr</h1>

  <h3 class="center-text">Find the performers you saw</h3>

  <p>There's so much talent on the SMP* <br > It's kinda hard finding those that you want to see. <br > Find them here.  *(SMP: Santa Monica Promenade)</p>
  <p>

    <%= link_to "Browse", posts_path, class: "btn btn-primary btn-lg" "specialCh", role: "button" %></p>


  <div class="actions">
    <%= link_to "Sign up", new_user_registration_path %>
  </div>

  <div class="actions">
    <%= link_to "Log In", new_user_session_path %>
  </div>

</div>